apiVersion: v1
kind: Service
metadata:
  name: pubmedmcp
  labels:
    app: pubmedmcp
spec:
  selector:
    app: pubmedmcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
